/*
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */


public class FindTheDifference {
    
    public char findTheDifference(String s, String t){

        /*
         * This uses bitwise operator, particularly the XOR operator(^) where similar values cancel out each other
         * The logic is the same as an XOR Switch
         * ex:
         * a^a = 0
         * 5^5 = 0
         * 1^0 = 1
         */

        char c = 0;

        for(char cs : s.toCharArray()) c ^= cs;
        for(char ct : t.toCharArray()) c ^= ct;

        return c;

        /*
            char x = 0;
            System.out.println(x);
            x ^= 'a'; //prints out a since 0 ^ a = a
            System.out.println(x);
            x ^= 'a'; //prints nothing since a ^ a = 0
            System.out.println(x);
            x ^= 'b'; //prints out b since a ^ b = b
            System.out.println(x);
         */
    }
}
